//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neudesic.AzureStorageExplorer.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neudesic.AzureStorageExplorer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Customers.
        /// </summary>
        public static string AllCustomersViewModel_DisplayName
        {
            get
            {
                return ResourceManager.GetString("AllCustomersViewModel_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Companies have no last name.
        /// </summary>
        public static string Customer_Error_CompanyHasNoLastName
        {
            get
            {
                return ResourceManager.GetString("Customer_Error_CompanyHasNoLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-mail address is invalid.
        /// </summary>
        public static string Customer_Error_InvalidEmail
        {
            get
            {
                return ResourceManager.GetString("Customer_Error_InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-mail address is missing.
        /// </summary>
        public static string Customer_Error_MissingEmail
        {
            get
            {
                return ResourceManager.GetString("Customer_Error_MissingEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name is missing.
        /// </summary>
        public static string Customer_Error_MissingFirstName
        {
            get
            {
                return ResourceManager.GetString("Customer_Error_MissingFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name is missing.
        /// </summary>
        public static string Customer_Error_MissingLastName
        {
            get
            {
                return ResourceManager.GetString("Customer_Error_MissingLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_Company
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_Company", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Not Specified).
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_NotSpecified
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_NotSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_Person
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_Person", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string CustomerViewModel_DisplayName
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer type must be selected.
        /// </summary>
        public static string CustomerViewModel_Error_MissingCustomerType
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_Error_MissingCustomerType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid customer..
        /// </summary>
        public static string CustomerViewModel_Exception_CannotSave
        {
            get
            {
                return ResourceManager.GetString("CustomerViewModel_Exception_CannotSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create new customer.
        /// </summary>
        public static string MainWindowViewModel_Command_CreateNewCustomer
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View all customers!.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllCustomers
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage Account.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewStorageAccount
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewStorageAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Azure Storage Explorer.
        /// </summary>
        public static string MainWindowViewModel_DisplayName
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View blobs.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewBlobs
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewBlobs", resourceCulture);
            }
        }

        //   Looks up a localized string similar to View queues.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewQueues
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewQueues", resourceCulture);
            }
        }

        //   Looks up a localized string similar to View tables.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewTables
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewTables", resourceCulture);
            }
        }

        //   Looks up a localized string similar to refresh.
        /// </summary>
        public static string MainWindowViewModel_Command_Refresh
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_Refresh", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_NewContainer
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewContainer", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyContainer
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyContainer", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_RenameContainer
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_RenameContainer", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteContainer
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteContainer", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_NewBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_RenameBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_RenameBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_UploadBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_UploadBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DownloadBlob
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DownloadBlob", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_NewQueue
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewQueue", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyQueue
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyQueue", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_RenameQueue
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_RenameQueue", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteQueue
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteQueue", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_NewMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_RenameMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_RenameMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteAllMessages
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_UploadMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_UploadMessage", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DownloadMessage
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DownloadMessage", resourceCulture);
            }
        }


        public static string MainWindowViewModel_Command_NewTable
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewTable", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyTable
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyTable", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_RenameTable
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_RenameTable", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteTable
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteTable", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_NewEntity
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewEntity", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_CopyEntity
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_CopyEntity", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteEntity
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteEntity", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DeleteAllEntitys
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DeleteEntity", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_UploadEntity
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_UploadEntity", resourceCulture);
            }
        }

        public static string MainWindowViewModel_Command_DownloadEntity
        {
            get
            {
                return ResourceManager.GetString("MainWindowViewModel_Command_DownloadEntity", resourceCulture);
            }
        }


    }
}
